/*
 * May 9th, 2020
 * Erika Graham
 * Zirboin Software: calculate how many of which coins can replace a certain amount of vrobits.
 */

/**
 *
 * @author kikag
 */
public class FrmZirboinSoftware extends javax.swing.JFrame {

    /**
     * Creates new form FrmZirboinSoftware
     */
    public FrmZirboinSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtVrobitsExchanged = new javax.swing.JTextField();
        btnExchange = new javax.swing.JButton();
        lblDrobzitTitle = new javax.swing.JLabel();
        lblClickwickTitle = new javax.swing.JLabel();
        lblGazoontightTitle = new javax.swing.JLabel();
        lblFrazointTitle = new javax.swing.JLabel();
        lblBlointointTitle = new javax.swing.JLabel();
        lblVrobitsTitle = new javax.swing.JLabel();
        lblDrobzits = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblBlointoints = new javax.swing.JLabel();
        lblVrobitsLeft = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        lblInstructions3 = new javax.swing.JLabel();
        lblExceptions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblTitle.setText("Zirboin ATM");

        jLabel1.setText("Vrobits to change:");

        btnExchange.setText("Exchange");
        btnExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExchangeActionPerformed(evt);
            }
        });

        lblDrobzitTitle.setText("Drobzits:");

        lblClickwickTitle.setText("Clickwicks:");

        lblGazoontightTitle.setText("Gazoontights:");

        lblFrazointTitle.setText("Frazoints:");

        lblBlointointTitle.setText("Blointoints:");

        lblVrobitsTitle.setText("Leftover Vrobits:");

        lblDrobzits.setText("0");

        lblClickwicks.setText("0");

        lblGazoontights.setText("0");

        lblFrazoints.setText("0");

        lblBlointoints.setText("0");

        lblVrobitsLeft.setText("0");

        lblInstructions.setText("Enter the amount of Vrobits");

        lblInstructions2.setText("you want to exchange and");

        lblInstructions3.setText("click \"Exchange\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrobzits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClickwicks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGazoontights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstructions)
                            .addComponent(lblInstructions3)
                            .addComponent(lblInstructions2)
                            .addComponent(jLabel1)
                            .addComponent(txtVrobitsExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBlointoints, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFrazoints, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDrobzitTitle)
                                    .addComponent(lblTitle)
                                    .addComponent(lblClickwickTitle)
                                    .addComponent(lblGazoontightTitle)
                                    .addComponent(lblFrazointTitle)
                                    .addComponent(lblBlointointTitle)
                                    .addComponent(lblVrobitsTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExchange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVrobitsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDrobzits, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDrobzitTitle))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblClickwicks, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClickwickTitle))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInstructions)
                                .addGap(8, 8, 8)
                                .addComponent(lblInstructions2)
                                .addGap(9, 9, 9)
                                .addComponent(lblInstructions3)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGazoontights, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGazoontightTitle))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFrazoints, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFrazointTitle))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtVrobitsExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlointoints, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlointointTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVrobitsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVrobitsTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExchange)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExchangeActionPerformed
        // Declaring all final variables
        final int DROBZIT = 100000;
        final int CLICKWICK = 50000; 
        final int GAZOONTIGHT = 10000;
        final int FRAZOINT = 1000;
        final int BLOINTOINT = 500;
        //declaring all variables subject to change
        int vrobitsToDrobzit=0; 
        int vrobitsToClickwick=0; 
        int vrobitsToGazoontight=0; 
        int vrobitsToFrazoint=0; 
        int vrobitsToBlointoint=0; 
        int vrobitsFinal=0;
        //variable to store user input
        String vrobitsInitial = txtVrobitsExchanged.getText();
        //check that the user entered variable is an integer
        try{
            Integer.parseInt(vrobitsInitial);
            lblExceptions.setText("");
        } catch(NumberFormatException nfe){
            lblExceptions.setText("Please enter valid data (An integer) \n" + nfe);
        }
        
        //perform calculations to convert vrobits to drobzit
        vrobitsToDrobzit = Integer.parseInt(vrobitsInitial) / DROBZIT;
        lblDrobzits.setText(String.valueOf(vrobitsToDrobzit));
        int VDRemainder = Integer.parseInt(vrobitsInitial) % DROBZIT ;
        
        //calculation to convert vrobits to clickwick
        vrobitsToClickwick = VDRemainder / CLICKWICK;
        lblClickwicks.setText(String.valueOf(vrobitsToClickwick));
        int VCRemainder = VDRemainder % CLICKWICK;
        
        //calculation to convert vrobits to gazoontight
        vrobitsToGazoontight = VCRemainder / GAZOONTIGHT;
        lblGazoontights.setText(String.valueOf(vrobitsToGazoontight));
        int VGRemainder = VCRemainder % GAZOONTIGHT;
        
        //calculations to convert vrobits to frazoint
        vrobitsToFrazoint = VGRemainder / FRAZOINT;
        lblFrazoints.setText(String.valueOf(vrobitsToFrazoint));
        int VFRemainder = VGRemainder % FRAZOINT;
        
        //calculation to convert vrobits to blointoint
        vrobitsToBlointoint = VFRemainder / BLOINTOINT;
        lblBlointoints.setText(String.valueOf(vrobitsToBlointoint));
        int VBRemainder = VFRemainder % BLOINTOINT;
        //input leftover vrobits
        lblVrobitsLeft.setText(String.valueOf(VBRemainder));
        
    }//GEN-LAST:event_btnExchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZirboinSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZirboinSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZirboinSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZirboinSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZirboinSoftware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExchange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBlointointTitle;
    private javax.swing.JLabel lblBlointoints;
    private javax.swing.JLabel lblClickwickTitle;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblDrobzitTitle;
    private javax.swing.JLabel lblDrobzits;
    private javax.swing.JLabel lblExceptions;
    private javax.swing.JLabel lblFrazointTitle;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblGazoontightTitle;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVrobitsLeft;
    private javax.swing.JLabel lblVrobitsTitle;
    private javax.swing.JTextField txtVrobitsExchanged;
    // End of variables declaration//GEN-END:variables
}
